---
title: "Experimental_Celltraq"
author: "Quadrant-4"
date: "September 29, 2016"
output: html_document
---
JMJPFU
29-Sept-2016

# Battery "5F47EE46-50C4-4A8A-8CAC-C483A7AEA880"

About 15 cycles of discharge over time. Voltage also drops when conductance has dropped. Voltage regains the original level when conductance rises. Need to look at how the voltage relates to current during the discharge cycle.


# Battery "1BB0B287-453B-4123-9DA5-AF6F6596B28F" > 600 : 700
The conductance shows a gradual decrease. The discharge profile of the voltage is more sharper here. The current and temperature dosent show any discernable patterns

# Batteries between 500 and 600
 054A7AD2-3658-42DD-98D0-454AC2EA3148 
 - Sharp discharge profiles for voltage. Drop in conductance is commensurate with a drop in current. Rise in volttemp and flux in temperature. 
 
# 11E51D42-5518-4649-A989-3BABDA09FD85 
 
  A cyclical trend with a rising trend by end of the time frame. Frequency of discharge around 34. Drop in Current around the time when the conductance is dropping. High flux in temperature around that period. High flux in voltage also around that time period.
  
<!-- #2F83C61C-2D65-45B2-ABF4-B48409BB5EA5 - Type 1 Trend : Cup like Trends -->
<!-- - A cup shaped cyclical trend. Current rises and then falls. The number of cup shaped observations are 3. The conductance retracts to its original level which might indicate replacement of the battery. So does the replacement trend indicate a failed battery ? Does these cyclical cup shaped discharge profile indicate failure ? -->
 
# 42E2FA79-F71B-4A36-A15F-CBB1700E9A6A - 
 
 This is a normal battery. The trend is a normal cyclical trend. Only observation is during the discharge cycle, the voltage stabilises to a constant value. Cant see any other prominent trend. 21 discharge cycles. But depth seems to be larger than other batteries where the conductance drop is large.
 
# F226E690-A1D7-4E8A-B02A-E468EC078BC5 

- A zig zag discharge trend with a rising trend in voltage corresponding to the drop in condctance. The discharge profile is sharper. Around 33 number of discharge cycles. With normal voltage showing a surge towards the area where the conductance falls and then a rapid fall.
 
# Batteries between 400 and 500

<!-- #0124308E-E6E8-4AE7-ABBE-E56561FE8CC0 - Type 1 Trend : Cup like Trends -->

<!-- This battery shows a cup shaped formulation for its Voltage discharge. the number of cups are less. The Voltage sustenance at the discharge level is for higher duration. There are also some instances of smaller frequencies. It is found that when the current is being varied, i.e when the current increases the voltage cup like shape is formed . However when the current is kep constant, the cycles involved are lesser. -->



<!-- #11E1F01B-39CA-41FC-AF37-863543C1A427 - Type 1 Trend : Cup like Trends -->

<!-- Voltage temperature readings were not present. The below zooms in on the increasing trend in current and the decreasing trend in voltage. When the current is kept constant there is a small cycle which is getting executed.  -->

<!--  Temp_bat_spot1 <- Temp_bat_consol %>% filter(Date1 > "2014-01-16 14:30:16 IST" & Date1 < "2014-01-16 14:32:15 IST") # -->

<!--  Also it needs to be noted that for replicating this problem, the temperature and voltage values are not present in the current data frame and therefore it needs to be introduced. -->

<!--  Also from a domain perspective, if the key variables are depth of discharge and also frequency of the cycles, this trend will meet the criteria. These trends shows number of cycles and achievement of the depth of discharge variables. -->

<!-- #14525931-DD65-4E15-A1C6-C1AF1588B9FC - Type II - Falling discharge voltage -->

<!-- This battery shows the trend of falling discharge voltage with many "w" shaped discharges and then finally a large drop in voltage which corresponds to the drop in conductance. The number of discharge cycles are larger.  -->

<!-- Temp_bat_spot2 <- Temp_bat_consol %>% filter(Date > "2012-09-23" & Date < "2012-09-25" ) -->

<!-- Same date profile of 24th Sept as the below battery and similar charachteristics with constant current of 22 -->


<!-- #21CACF45-93A9-40BC-9298-3987DD1881F8 - Type II - Falling discharge voltage -->


<!-- - Lot of cyclic frequencies followed by a big drop in voltage. However, it is not beyond the 80% limit -->

<!-- This battery shows the second trend, where there are many cycles of discharge with some sharp discharge profiles. The voltage then falls in conjunction with the falling conductance. However the depth of discharge is never met. The discharge profile is represented as a "w" kind of profile and this is achieved over a period of day.  -->

<!-- Temp_bat_spot2 <- Temp_bat_consol %>% filter(Date > "2012-09-23" & Date < "2012-09-25" ) -->

<!-- The above code is a representation of the close up of a "w" trend in voltage discharge. The current is kept constant. There are two cycles over time frame of a day.  -->


<!-- #2567A348-2E85-4C54-B24E-C69D3F85ACF3 - Type 1 Trend : Cup like Trends : No VT -->
<!-- Constant conductance battery. This type again, similar to the once see above. The discharge voltage shows some cup like discharge profile. There are also some sharp discharge profiles for relatively constant current. However even the large cup like voltage profile are smaller wave like discharge cycles.  -->

<!-- Charachteristics I -->
<!-- Temp_bat_spot1 <- Temp_bat_consol %>% filter(Date1 > "2014-01-16 14:30:16 IST" & Date1 < "2014-01-16 14:32:15 IST") -->

<!-- Characteristics II -->
<!-- Temp_bat_spot2 <- Temp_bat_consol %>% filter(Date > "2014-03-25" & Date < "2014-03-27" ) -->

<!-- The second characteristics is for the shorter discharge profile in the whole section. The discharge voltage dips and shows a gradual rise. This profile is different from the long cup shaped profile with many smaller frequency profiles when the current keeps rising. -->


#

<!-- #58CC8861-5D3C-4987-9DFF-F27042E5C1DF - Type II - Falling discharge voltage -->
<!-- The general trend is drop in conductance almost to 0 level, and then a drop in voltage lower than the 80% level. It goes even to zero. So the depth of discharge is attained. So has this battery failed ?? -->

<!-- Charachteristics I : Hockey stick profile -->

<!-- Temp_bat_spot2 <- Temp_bat_consol %>% filter(Date > "2013-03-03" & Date < "2013-03-05" ) # -->
<!-- The above shows a hockey stick profile. However, when the current drops the voltage also rises as expected. Otherwise the voltage profile shows a constant profile for the voltage. -->

<!-- Characteristics II : "Ro" profile -->
<!-- Temp_bat_spot2 <- Temp_bat_consol %>% filter(Date > "2013-06-24" & Date < "2013-06-26" ) #  -->
<!-- Shows the sudden dip and then rising and then constant profile. When the current is dropped then the voltage picks up and when the current is kept constant, the voltage also remains constant. -->

<!-- Charachteristics III : A gradual drop, 0 voltage and bouncing -->

<!-- Temp_bat_spot2 <- Temp_bat_consol %>% filter(Date > "2014-03-25"  )  -->
<!-- The surprising fact about this profile is that the discharge voltage attains a 0 voltage and then it rises back when the current is raised. Ideally when the current drawn is raised the voltage has to be reduced. -->







# 




<!-- # CF6432BD-8444-4D5E-838A-3B7315624036 - Type 1 Trend : Cup like Trends : No VT -->

<!-- Constant conductance battery. This type again, similar to the once see above. The discharge voltage shows some cup like discharge profile. There are also some sharp discharge profiles for relatively constant current. However even the large cup like voltage profile are smaller wave like discharge cycles. -->



# #################################### JMJPFU ####################3
# Oct 25

Observation

# JMJPFU 

# Oct 28
Conductance 
gradual :5,6,8,9,11,13,16,18:20
Drop & Retract :
Drop & Small retract :
Drop & Stay : 14
Low - Rise - Gradual drop :3
No Trend : 1;2,4,7,10,12,15,17
Condrop : 
.2 - .3 : 
.6 - .7 : 4
.8 and .70 :1,3,7,12,15
.8 - .85 :11
> .85 : 2,5,6,8:10,13;14,16:20

DOD 
At .25 level :
At . 5 level : Most : 
At .6 level : Some :
Below .75 : Oneoff : Some :  Most : All : 
Between .8 - .75  :Lot :  Some :  Little : Oneoff: 
Between .8 - .85 : Oneoff:  Most : Some:  All: 
Above .85 _ little : Some : Most : All : 1;5,6:10,11;15,16;20





